# Generated by Django 4.1.2 on 2023-11-25 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='isFake',
        ),
    ]
