# Generated by Django 4.1.2 on 2023-11-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_rename_video_video_video_file_remove_video_isfake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='userid',
        ),
    ]
